registry:
    url: https://candidate-registry.fedoraproject.org
database:
    postgres:
        url: postgres://flagstate:mypassword@localhost:7432/flagstate?sslmode=disable
interval:
    fetch_all: 1h
    garbage_collect: 30m

