version: '2.1'

volumes:
    db:
    registry:
    tls:

services:
    db:
        image: postgres
        hostname: db
        ports:
            - 7432:5432
        environment:
            - POSTGRES_DB=flagstate
            - POSTGRES_USER=flagstate
            - POSTGRES_PASSWORD=mypassword
        volumes:
            - db:/var/lib/postgresql/data:z

    registry:
        image: docker.io/owtaylor/registry-oci:latest
        ports:
            - 7000:5000
        volumes:
            - registry:/var/lib/registry:z
            - ./services/registry/config.yml:/etc/docker/registry/config.yml:z

    index:
        build: .
        hostname: index
        ports:
            - 8088:8088

    frontend:
        build: services/frontend
        ports:
            - 7080:80
            - 7443:443
        volumes:
            - ${TEST_DATA:-./test-data}:/mnt/test-data:z
            - tls:/etc/pki/tls:z
