#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

changed=$(git diff-index --cached --name-only HEAD)
reformat=""
for f in $changed ; do
    case $f in
	vendor/*)
	    continue
	    ;;
	*.go)
	    res=$(git show :$f | gofmt -l)
	    if [ "$res" != "" ] ; then
		reformat="$reformat $f"
	    fi
	    ;;
    esac
done

if [ "$reformat" != "" ] ; then
    echo "Staged changes have formatting problems. Please run:"
    echo "   go fmt" $reformat
    exit 1
fi
