registry:
    url: http://registry:5000
    public_url: /
components:
    web_ui: true
    assert_endpoint: true
events:
    token: "OPEN_SESAME"
database:
    postgres:
        url: postgres://flagstate:mypassword@db:5432/flagstate?sslmode=disable
cache:
    max_age_index: 1s
    max_age_html: 1s
interval:
    fetch_all: 1h
    garbage_collect: 30m
